import 'package:flutter/material.dart';

extension IconExtension on IconData {
  String toLabelString() {
    return switch(this) {
      Icons.account_balance => 'Account Balance',
      Icons.account_box => 'Account Box',
      Icons.ad_units => 'AD Units',
      Icons.alarm => 'Alarm',
      Icons.agriculture => 'Agriculture',
      Icons.airplanemode_active => 'Airplane Mode Active',
      Icons.airplay => 'Airplay',
      Icons.airport_shuttle => 'Airport Shuttle',
      Icons.alarm => 'Alarm',
      Icons.anchor => 'Anchor',
      Icons.android => 'Android',
      Icons.apartment => 'Apartment',
      Icons.apple => 'Apple',
      Icons.architecture => 'Architecture',
      Icons.attach_money => 'Attach Money',
      Icons.auto_stories => 'Auto Stories',
      Icons.av_timer => 'AV Timer',
      Icons.balance => 'Balance',
      Icons.beach_access  => 'Beach Access',
      Icons.brush => 'Brush',
      Icons.bug_report => 'Bug Report',
      Icons.build => 'Build',
      Icons.cake => 'Cake',
      Icons.call => 'Call',
      Icons.camera_alt => 'Camera Alt',
      Icons.dining => 'Dining',
      Icons.directions_bike => 'Directions Bike',
      Icons.directions_boat => 'Directions Boat',
      Icons.directions_bus => 'Directions Bus',
      Icons.directions_car => 'Directions Car',
      Icons.elderly => 'Elderly',
      Icons.elderly_woman => 'Elderly Woman',
      Icons.emoji_events => 'Emoji Events',
      Icons.headphones_rounded => 'Headphones Rounded',
      Icons.help => 'Help',
      Icons.house => 'House',
      Icons.import_export => 'Import/Export',
      Icons.info => 'Info',
      Icons.language => 'Language',
      Icons.laptop => 'Laptop',
      Icons.lock => 'Lock',
      Icons.notifications => 'Notifications',
      Icons.percent => 'Percent',
      Icons.cancel_presentation_outlined => 'Cancel Presentation',
      Icons.school => 'School',
      Icons.show_chart => 'Show Chart',
      Icons.star => 'Star',
      _ => ''
    };
  }
}