import 'package:flutter/material.dart';

class IconProvider {
  static List<IconData> getAll() {
    return [
      Icons.account_balance,
      Icons.account_box,
      Icons.ad_units,
      Icons.agriculture,
      Icons.airplanemode_active,
      Icons.airplay,
      Icons.airport_shuttle,
      Icons.alarm,
      Icons.anchor,
      Icons.android,
      Icons.apartment,
      Icons.apple,
      Icons.architecture,
      Icons.attach_money,
      Icons.auto_stories,
      Icons.av_timer,
      Icons.balance,
      Icons.beach_access,
      Icons.brush,
      Icons.bug_report,
      Icons.build,
      Icons.cake,
      Icons.call,
      Icons.camera_alt,
      Icons.dining,
      Icons.directions_bike,
      Icons.directions_boat,
      Icons.directions_bus,
      Icons.directions_car,
      Icons.elderly,
      Icons.elderly_woman,
      Icons.emoji_events,
      Icons.headphones_rounded,
      Icons.help,
      Icons.house,
      Icons.import_export,
      Icons.info,
      Icons.language,
      Icons.laptop,
      Icons.lock,
      Icons.notifications,
      Icons.percent,
      Icons.cancel_presentation_outlined,
      Icons.school,
      Icons.show_chart,
      Icons.star
    ];
  }
}
