name: mp2_tracker
description: "Your personal Pag-Ibig MP2 savings tracker."
publish_to: 'none'
version: 1.0.8

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bcrypt: ^1.1.3
  file_picker: ^6.2.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  google_mobile_ads: ^3.1.0
  intl: ^0.19.0
  path: ^1.9.0
  permission_handler: ^11.3.0
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: 'launcher_icon'
  image_path: 'assets/logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
